### ISSUE TITLE
Polluted master 

### ISSUE THREAD

**Issue by justin0022** [JJ-Coding-Emporium/jj-coding-emporium#10]
Before: 
![before](https://user-images.githubusercontent.com/8836578/49746257-a8403500-fc55-11e8-878e-c9a83313b142.PNG)
After:
![after](https://user-images.githubusercontent.com/8836578/49746263-ad04e900-fc55-11e8-8e4c-c5da6b220198.PNG)

**Comment by jordancoblin** [comment]
Reverted the commit that added all those **evil** generated files.

Before the evil commit (un-polluted):
![image](https://user-images.githubusercontent.com/7538750/49756922-f7935f00-fc6f-11e8-92b4-0bfd9a1b32b1.png)

Now:
![image](https://user-images.githubusercontent.com/7538750/49756912-f104e780-fc6f-11e8-955e-136914427c65.png)

**Comment by justin0022** [comment]
👍
